[package]
name = "video-editor"
version = "0.4.0"
description = "Video Editor backend"
edition = "2021"

[lib]
name = "video_editor_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "stream", "json"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "fs", "io-util", "sync", "time"] }
futures-util = "0.3"
zip = { version = "2", features = ["deflate"] }
percent-encoding = "2"

[profile.release]
codegen-units = 16
lto = false
